export const portfolioContext = [
  "User Profile:",
  "- Name: Roshni Kumari",
  "- Role: Full Stack Developer & Competitive Programmer",
  "- Education: B.Tech Computer Science Engineering, National Institute of Technology Jamshedpur (2023 – 2027)",
  "- Academic Excellence: CGPA 9.34/10.0; consistently ranked in the top 0.85% of a 700+ student batch",
  "- School: Dev Sangha National School. Class 12 CBSE (2020-2022): 96.2%, 5th rank in district. Class 10 CBSE (2018-2020): 97.2%, 4th rank in district.",
  "- Problem Solving: Solved 1200+ problems across Codeforces, CodeChef, LeetCode, and GeeksforGeeks.",
  "- Location: Jamshedpur, Jharkhand, India",
  "- Phone: +91 8709758581",
  "- Email: ",
  "- GitHub: https://github.com/roshnikumari-21",
  "- LinkedIn: https://www.linkedin.com/in/roshni-kumari-2aa61928a/",
  "",
  "Experience:",
  "1. SDE Intern at Flipkart, Bengaluru (On-site), May 2026 - Jul 2026",
  "   - Developed and shipped production APIs, automated compliance workflows, and contributed to backend services powering Flipkart's Compliance Management Platform.",
  "   - Improved infrastructure security through secret migration, participated in production deployments, and enhanced operational dashboards.",
  "   - Tech: Java, Spring Boot, Python, MySQL, TiDB, Kubernetes, Helm",
  "2. SDE Intern at Flipkart, Bengaluru (On-site), May 2025 - Jul 2025",
  "   - Enhanced the Content Management Platform (Flipkart Minutes - Neolite ADP UI), improving automation efficiency by 30% and streamlining internal workflows.",
  "   - Built reusable UI components, reducing manual processes across 3 teams and accelerating feature rollout.",
  "   - Tech: React, Redux, Node.js, Java, Dropwizard, Cursor AI",
  "",
  "Ratings:",
  "- Codeforces: Pupil, 1227 (handle: roshniKumari) https://codeforces.com/profile/roshniKumari",
  "- CodeChef: 3 star, 1651 (handle: roshnikumari21) https://www.codechef.com/users/roshnikumari21",
  "- LeetCode: 1728 (handle: Roshniee) https://leetcode.com/Roshniee",
  "",
  "Achievements:",
  "- Top 20 finalist (out of 50K+ applicants) - Flipkart Runway Season 5 Internship Program, May 2025",
  "- Finalist at BNY Mellon Code Divas - Season 2025, Mar 2025",
  "- College rank 12 in CodeKarma coding contest at NIT Jamshedpur, Nov 2024",
  "- Solved 1200+ problems across Codeforces, CodeChef, LeetCode, GFG",
  "- Actively participated in the Competitive Programming Summer Camp 2024 held by IICPC, May 2024",
  "- Open-source contributor at GirlScript Summer of Code, Apr 2024",
  "- Consistently ranked in the top 0.85% of a 700+ student batch based on CGPA",
  "- Selected for Amazon ML Summer School 2026, Jul 2026",
  "",
  "Technical Skills:",
  "- Programming Languages: C, C++, Python, JavaScript, TypeScript",
  "- Problem Solving: Data Structures and Algorithms, Competitive Programming",
  "- Web Technologies: HTML, CSS, React.js, Tailwind CSS, Bootstrap, Express.js, Next.js, Node.js",
  "- Tools/Platforms: Git, GitHub, Terminal, Windows, VS Code, Postman, Vercel, Render",
  "- Databases: MongoDB, MySQL, Redis",
  "- CS Fundamentals: Object-Oriented Programming (OOPs), DBMS, Operating System, Computer Networks",
  "- Also used in internships: Java, Spring Boot, Kubernetes, Helm, TiDB, Redux, Dropwizard, Cursor AI",
  "",
  "Projects:",
  "1. Codophile: Visual CSS Playground and Tailwind Generator",
  "   Interactive developer tool for real-time CSS experimentation, visual previews, and CSS/Tailwind code generation.",
  "   Tech: Next.js 15, React 19, TypeScript, Tailwind CSS v4, Framer Motion, Monaco Editor, MongoDB",
  "   GitHub: https://github.com/roshnikumari-21/codophile-v2",
  "   Live: https://beta.codophile.in/",
  "2. KnightMare: Chess Web App with AI and Leaderboard (Mar 2025)",
  "   Chess platform allowing users to play against the computer with authentication and leaderboard tracking.",
  "   Tech: MongoDB, Express.js, React, Node.js, Tailwind CSS, Stockfish",
  "   GitHub: https://github.com/roshnikumari-21/KnightMare",
  "   Live: https://knightmare.onrender.com/",
  "3. Smart-Serve: AI-Powered Community Issue and Volunteer Management System (Jan 2026)",
  "   MERN platform using Gemini AI to analyze community reports, classify issues, and generate priority scores using urgency, impact, category, and recency.",
  "   Tech: MongoDB, Express.js, React.js, Node.js, TypeScript, Tailwind CSS, Gemini AI",
  "   GitHub: https://github.com/roshnikumari-21/Smart-Serve-System",
  "   Live: https://smart-serve-system.vercel.app",
  "4. StyleSync & Swyft: Myntra Hackerramp AI fashion platform with virtual try-on and personalized discovery.",
  "   Tech: React, Node.js, TensorFlow.js, Python, OpenCV, Generative AI, Computer Vision, MongoDB",
  "   GitHub: https://github.com/roshnikumari-21/MyntraHackerRamp",
  "   Live: https://myntra-hackerramp-five.vercel.app/",
  "5. ProfPort: Portfolio management system for professors with admin controls and dynamic content.",
  "   Tech: MongoDB, Express.js, React, Node.js, Tailwind CSS",
  "   GitHub: https://github.com/roshnikumari-21/ProfPort",
  "   Live: https://profport.onrender.com/",
  "6. AuraPredict: ML web app for early cancer prediction using diagnostic data.",
  "   Tech: Python, Streamlit, Pandas, Scikit-learn",
  "   GitHub: https://github.com/roshnikumari-21/AuraPredict",
  "   Live: https://aurapredict.streamlit.app/",
  "7. Stackelberg Competition Research: genetic algorithms for hierarchical decision-making in supply chain optimization.",
  "   Tech: Python, DEAP, SciPy, NumPy, Genetic Algorithms",
  "   GitHub: https://github.com/roshnikumari-21/Capstone_GA_1",
  "8. DSA Solutions & Interview Prep: topic-wise DSA solutions for interview preparation.",
  "   Tech: C++, Python, Java, Algorithms, Data Structures",
  "   GitHub: https://github.com/roshnikumari-21/DSA",
  "",
  "Positions of Responsibility:",
  "- Programming Club of NIT Jamshedpur | Member | Apr 2025 - Present",
  "- Society of Computer Science and Engineering (SCSE) | General Secretary | Feb 2025 - Present | https://scse-nitjsr.in/",
  "- Class Representative | Sep 2024 - Present",
].join("\n");
